### ISSUE TITLE
Unable to run the application (.exe)

### ISSUE THREAD

**Issue by Gauthamkan** [vinhloc1996/Decrypt-PluralSight-Videos#13]
First of all , thanks for building this tool.
I have followed all your instructions and the moment I run the exe it say's "Press any key to exit".
I am unable to type the command line. 
The application immediately exits each time. Also, my machine has .Net frame work 4.5.2 installed and I have extracted your latest build V1.2.
Could you please help me resolve this issue.
I have attached a screenshot of the error I am facing.
![errorps](https://user-images.githubusercontent.com/38757666/52920472-bb950e00-3332-11e9-9e39-0fed23379ee6.PNG)

**Comment by vinhloc1996** [comment]
Hi @Gauthamkan, please don't run this directly by opening the .exe file. This tool opens only by the command line, which means you have to use the command line interface and navigate to the extracted folder, run the command such as `DecryptPluralSightVideos /HELP` to see the options or read the sample command [here](https://github.com/vinhloc1996/Decrypt-PluralSight-Videos#example-execute-commands). If you have any other issues, just comment here and I will gladly help you.
