### ISSUE TITLE
trying to use it on windows

### ISSUE THREAD

**Issue by ThunderAxe1782** [vinhloc1996/Decrypt-PluralSight-Videos#14]
i dont have an E drive on my computer
```
Error occured: Attempted to access a path that is not on the disk.
   at DecryptPluralSightVideos.Decryptor.DecryptAllFolders(String folderPath, String outputFolder) in E:\Work\DecryptPluralSightVideos\DecryptPluralSightVideos\Decryptor.cs:line 111
   at DecryptPluralSightVideos.Program.Main(String[] args) in E:\Work\DecryptPluralSightVideos\DecryptPluralSightVideos\Program.cs:line 36
```

**Comment by vinhloc1996** [comment]
Hi @ThunderAxe1782, you don't need the E drive on the computer, it could be any drive letter that available on your computers, such as `C` drive or `D` drive, just change the output path that suitable for your computer.

**Comment by ThunderAxe1782** [comment]
the drive appearing in the error E:\Work\DecryptPluralSightVideos\DecryptPluralSightVideos\Program.cs:line 36

while i dont have that, i thought u hard-coded that path or something

**Comment by vinhloc1996** [comment]
No, I don't hard code any path. Could you provide me the command you used? I will figure out what wrong it is.

**Comment by martinkupka** [comment]
I have the same issue with the app and E: drive. Issue is exactly the same as @ThunderAxe1782 described. I also don't have E: drive nor the E: drive was specified in the command.

**Comment by vinhloc1996** [comment]
Hi @martinkupka, could you please provide me the entire command you used? If you used only the drive letter, you can add one `\` in the output path. Example: `/OUT "F:\\"` will be corrected, while `/OUT "F:\"` won't. Another example: `/OUT "F:\Output"` will be corrected for output the course folders in the `Output` directory, while `/OUT "F:\\Output"` won't. I will update this scenario in the ReadMe file. If you have any other issues, just comment here and I will help you.
