### ISSUE TITLE
Finding Course Name

### ISSUE THREAD

**Issue by DamruJi** [vinhloc1996/Decrypt-PluralSight-Videos#16]
I have moved the downloaded courses to another location as my Hard Disk was on low space. I  also deleted the course list from Pluralsight Player, now decryptor is unable to decrypt the courses even though I have moved them to original location.
There are total 14 courses and I can't even remember which courses I downloaded, is there any way to get the course name from the folders which are in download location. I can see that each course has been downloaded in a separate folder.

**Comment by vinhloc1996** [comment]
Hi @DamruJi, I cannot imagine what you described above, could you please take a photo of the course folder, or write down a list of steps to reproduce your problem?

**Comment by DamruJi** [comment]
1. Pluralsight Courses are stored at this location: "**C:\Users\Yugal\AppData\Local\Pluralsight\courses**"
2. My **C Drive** was almost full, so I moved the download courses to another location before decrypting them.
3. After freeing up disk space on **C Drive** I moved the courses back to its original location and tried to use your decryptor.
4. Now when I am running the decryptor, it is not decrypting the courses, I have attached the screenshot and course folder screenshot.
![Capture](https://user-images.githubusercontent.com/49745607/56355290-95d19b80-61f3-11e9-912f-1c25b7443827.JPG)
![Capture1](https://user-images.githubusercontent.com/49745607/56355296-979b5f00-61f3-11e9-84e2-8a12f5c55236.JPG)

**Comment by vinhloc1996** [comment]
Thanks for your detail, but could you send me the command you run? Did you run the /RM flag? Because it will remove the course in the database sqlite.

**Comment by DamruJi** [comment]
DecryptPluralSightVideos /F "C:\Users\Yugal\AppData\Local\Pluralsight\courses" /DB "C:\Users\Yugal\AppData\Local\Pluralsight\pluralsight.db" /TRANS /RM

**Comment by vinhloc1996** [comment]
One more thing, inside the course folders, have all the videos been decrypted? and could you upload the database file in this, I will check your database to see if I can recover the course name or not because I saw you run `/RM` flag. The location of pluralsight's database `C:\Users\Yugal\AppData\Local\Pluralsight\pluralsight.db`. Thank you.

**Comment by DamruJi** [comment]
Actually not a single Course has been decrypted, that is the reason I want to know the course names so that I can re-download them. I have attached the zip file which contains the Database.
Is there any way to decrypt the courses when database has been removed?
[pluralsight.zip](https://github.com/vinhloc1996/Decrypt-PluralSight-Videos/files/3094823/pluralsight.zip)

**Comment by vinhloc1996** [comment]
I will try to find those courses, If I can find anything, I will update here.

**Comment by vinhloc1996** [comment]
I can find some course name, the number is not exactly matched with your number of courses, but better than nothing, you can start again by this clue. These are:

1. [SQL Server: Deadlock Analysis and Prevention](https://www.pluralsight.com/courses/sqlserver-deadlocks)
2. [SQL Server: Indexing for Performance](https://www.pluralsight.com/courses/sqlserver-indexing-for-performance)
3. [SQL Server 2012 Querying (70-461) Part 2](https://www.pluralsight.com/courses/sql-server-2012-querying-pt2)
4. [T-SQL Window Functions](https://www.pluralsight.com/courses/tsql-window-functions)
5. [SQL Server 2008 Database Development (70-433) Part 2](https://www.pluralsight.com/courses/sql-server-2008-database-development-pt2)
6. [SQL Server 2012: Nonclustered Columnstore Indexes](https://www.pluralsight.com/courses/sql-server-2012-nonclustered-columnstore-indexes)
7. [SQL Server: Index Fragmentation Internals, Analysis, and Solutions](https://www.pluralsight.com/courses/sqlserver-index-fragmentation-internals-analysis-solutions)
8. [SQL Server: Optimizing Stored Procedure Performance](https://www.pluralsight.com/courses/sqlserver-optimizing-stored-procedure-performance)
9. [Developer's Guide to SQL Server CLR Integration](https://www.pluralsight.com/courses/developers-guide-sql-server-clr)
10. [Designing and Implementing SQL Server Tables and Views](https://www.pluralsight.com/courses/sqlserver-tables-view-designing-implementing)
11. [C# Design Strategies](https://www.pluralsight.com/courses/csharp-design-strategies)
12. [XML Fundamentals in C#](https://www.pluralsight.com/courses/csharp-xml-fundamentals)
13. [Getting Started with Asynchronous Programming in .NET](https://www.pluralsight.com/courses/getting-started-with-asynchronous-programming-dotnet)
14. [SOLID Principles of Object Oriented Design](https://www.pluralsight.com/courses/principles-oo-design)
15. [Beginning C# Collections](https://www.pluralsight.com/courses/csharp-collections-beginning)
16. [Refactoring Fundamentals](https://www.pluralsight.com/courses/refactoring-fundamentals)
17. [ASP.NET Core Fundamentals](https://www.pluralsight.com/courses/aspnet-core-fundamentals)
18. [Building Your First ASP.NET Core 2 MVC Application](https://www.pluralsight.com/courses/building-first-aspdotnet-core-2-mvc-application)
19. [Building an API with ASP.NET Web API](https://www.pluralsight.com/courses/aspnet-web-api-building)

**Comment by DamruJi** [comment]
Thanks for your help, all these courses were related to SQL Server, and they are in the list given by you.
