### ISSUE TITLE
Video titles not always displayed in version 1.3

### ISSUE THREAD

**Issue by smithy49** [vinhloc1996/Decrypt-PluralSight-Videos#18]
Some of the decrypted videos have no title, see below.
**3.mp4**
However the title is present in pluralsight.db.

**Comment by vinhloc1996** [comment]
Hi @smithy49, I think the path is too long and may exceed the limit. Here is the block of code that will detect the path exceed the limit length and rename it.
https://github.com/vinhloc1996/Decrypt-PluralSight-Videos/blob/be5072e785eb7e336834ab3230a066e68baa3ace/DecryptPluralSightVideos/Decryptor.cs#L226-L231

**Comment by smithy49** [comment]
Hi @vinhloc1996, yes I think you're right. 
Windows warned me of file names being too long.
I thought Windows 10 had resolved this issue but apparently not.
Thanks again.
