### ISSUE TITLE
Some videos are duplicated and some are missing.

### ISSUE THREAD

**Issue by casperbear** [vinhloc1996/Decrypt-PluralSight-Videos#6]
Some videos are duplicated and some are missing as the result of the program execution. Which videos are duplicated and which ones are missing is pretty much random. I think it's because
`playingFileStream.Clone(out iStream);`
updates iStream which is Decryptor instance field while it should be a variable local to the same scope as newPath.

`foreach (Clip clip in listClips)`
and
`WriteTranscriptFile(clip.ClipId, newPath);`
combination is also suspicious. I'm not sure if it's going to capture and use proper clip value.

I mean, it's related to the fact that
`DecryptVideo(iStream, newPath);`
and
`WriteTranscriptFile(clip.ClipId, newPath);`
are executed in a task.

**Comment by vinhloc1996** [comment]
Hi @casperbear, thanks for providing the information. Can I have the course name? I will test it later and find out what go wrong.

**Comment by casperbear** [comment]
@vinhloc1996 Sure, for example course "C++ Advanced Topics"

**Comment by vinhloc1996** [comment]
Hi @casperbear, I have tested the course you provide but it seems to work normally. I don't find any duplicate or missing files, so I guess this error may go randomly or you might have turned off the command line before it finishes. Anyway, you can use it without `/RM` flag to keep the course info still in the database. Then checking the course files if it's missing or duplicating, if yes rerun the command to re-decrypt it again. Thanks again for the info.

**Comment by casperbear** [comment]
Hi @vinhloc1996 Yes, as I reported in the initial thread it's a random error, related to the fact that actual decrypting is done in parallel threads and sometimes race bug happens because two tasks access the same iStream object. So the end result is: there is proper number of generated files (both mp4 and srt), they all have proper names, but some files' content is duplication of some other files' content. Anyways, thank you for uploading the source code! I've just temporarily disabled multi-threading and successfully decoded 29 courses in one run without a single error. I'll close this now.

**Comment by josephDoss2016** [comment]
Hi, How was this issue closed. I still see this issue in the new build. @casperbear how did you disable  multithreading

**Comment by casperbear** [comment]
Hi @josephDoss2016 At the time, I downloaded source code, commented out several lines and ran it locally (from Visual Studio). Of course since there is a new build, lines may not look exactly the same.

                        //Semaphore.Wait();
                        //TaskList.Add(Task.Run(() =>
                        //{
                            // Write the decrypted video from istream to new file mp4
                            DecryptVideo(iStream, newPath);
                            if (Options.CreateTranscript)
                            {
                                // Generate transcript file if user ask
                                WriteTranscriptFile(clip.ClipId, newPath);
                            }
                        //    lock (SemaphoreLock)
                        //    {
                        //        Semaphore.Release();
                        //    }
                        //}));

**Comment by josephDoss2016** [comment]
Thanks @casperbear

**Comment by vinhloc1996** [comment]
Hi @casperbear, I've found the issue now and I'm sorry for not finding this issue right after you've reported. Also, I've published build version 1.3 to solve this. Your solution is correct, I've temporary disable multithread function to solve the issue. Sorry for the late solving problem.
