### ISSUE TITLE
mac is on the roadmap?

### ISSUE THREAD

**Issue by elnemesisdivina** [vinhloc1996/Decrypt-PluralSight-Videos#7]
Hi just wonder if MAC OS is on the roadmap to use this tool?

**Comment by vinhloc1996** [comment]
Hi @elnemesisdivina, at the current point, I don't plan for running this tool on MacOS. But in future. I will try to parse it to .Net Core application to run cross-platform. I will update in this issue If I have a plan about this. Anyway, thank you for recommending new features.
