### ISSUE TITLE
Not outputting Video. Stops decrypting.

### ISSUE THREAD

**Issue by dderoia** [vinhloc1996/Decrypt-PluralSight-Videos#8]
I enter the correct command line options ....
D:\Video\PluralsightDecode>DecryptPluralSightVideos /F "D:\Video\PluralsightCourse\courses" /DB "C:\Users\Darren\AppData\Local\Pluralsight\Pluralsight.db" /OUT "D:\Video\Pluralsight"

I get the following ... 5 x files decrypted (except they are not - there is no video output). Then the last one just sits there and does not progress. Simply puts up a message [Start to Decrypt File "2d563dcd-656b-44d7-a8e7-abc1c9d4afc6.psv"]

Start to decrypt all courses...
The Database Connection has been open completely.
Start to Decrypt File "4b876f73-07c3-4500-91f9-85fd50b12471.psv"
Decryption File "0. Introductions and Agenda.mp4" successfully
Start to Decrypt File "3c03d6fa-74a7-4c92-8f9d-c6b14e047ded.psv"
Decryption File "1. The pitfalls of concurrency.mp4" successfully
Start to Decrypt File "10bd0be0-b14e-4ed0-a30e-b8a51855a876.psv"
Decryption File "2. Correctness guarantees- safety, liveness.mp4" successfully
Start to Decrypt File "7ac1713e-0308-439b-8262-69bb5e752548.psv"
Decryption File "3. Terminology- race conditions, critical sections.mp4" success
fully
Start to Decrypt File "658a5a90-4c31-4989-9041-22ed5d788d79.psv"
Decryption File "4. Race conditions involving shared resources.mp4" successfully

Start to Decrypt File "2d563dcd-656b-44d7-a8e7-abc1c9d4afc6.psv"

**Comment by vinhloc1996** [comment]
Hi @dderoia, could you provide the course name/course link for the testing purpose?

**Comment by dderoia** [comment]
That is not the case.  The directory I specified is correct. "C:\Users\Darren\AppData\Local\Pluralsight\courses"
I have set the options on the Pluralsight app to save the courses to that location and that location is where they are.

**Comment by dderoia** [comment]
And as verification :  I reset the location to default ... and downloaded the course again. Rerun the command sand exactly the same outcome. No files and this is the command window text  ...

D:\Video\PluralsightDecode>DecryptPluralSightVideos /F "C:\Users\Darren\AppData\
Local\Pluralsight\courses" /DB "C:\Users\Darren\AppData\Local\Pluralsight\Plural
sight.db" /OUT "D:\Video\Pluralsight"
Start to decrypt all courses...
The Database Connection has been open completely.

Start to Decrypt File "4b876f73-07c3-4500-91f9-85fd50b12471.psv"
Decryption File "0. Introductions and Agenda.mp4" successfully
Start to Decrypt File "3c03d6fa-74a7-4c92-8f9d-c6b14e047ded.psv"
Decryption File "1. The pitfalls of concurrency.mp4" successfully
Start to Decrypt File "10bd0be0-b14e-4ed0-a30e-b8a51855a876.psv"
Decryption File "2. Correctness guarantees- safety, liveness.mp4" successfully
Start to Decrypt File "7ac1713e-0308-439b-8262-69bb5e752548.psv"
Decryption File "3. Terminology- race conditions, critical sections.mp4" success
fully
Start to Decrypt File "658a5a90-4c31-4989-9041-22ed5d788d79.psv"
Decryption File "4. Race conditions involving shared resources.mp4" successfully

Start to Decrypt File "2d563dcd-656b-44d7-a8e7-abc1c9d4afc6.psv"

D:\Video\PluralsightDecode>DecryptPluralSightVideos /F "C:\Users\Darren\AppData\
Local\Pluralsight\courses" /DB "C:\Users\Darren\AppData\Local\Pluralsight\Plural
sight.db" /OUT "D:\Video\Pluralsight"
Start to decrypt all courses...
The Database Connection has been open completely.

Start to Decrypt File "4b876f73-07c3-4500-91f9-85fd50b12471.psv"
Decryption File "0. Introductions and Agenda.mp4" successfully
Start to Decrypt File "3c03d6fa-74a7-4c92-8f9d-c6b14e047ded.psv"
Decryption File "1. The pitfalls of concurrency.mp4" successfully
Start to Decrypt File "10bd0be0-b14e-4ed0-a30e-b8a51855a876.psv"
Decryption File "2. Correctness guarantees- safety, liveness.mp4" successfully
Start to Decrypt File "7ac1713e-0308-439b-8262-69bb5e752548.psv"
Decryption File "3. Terminology- race conditions, critical sections.mp4" success
fully
Start to Decrypt File "658a5a90-4c31-4989-9041-22ed5d788d79.psv"
Decryption File "4. Race conditions involving shared resources.mp4" successfully

Start to Decrypt File "2d563dcd-656b-44d7-a8e7-abc1c9d4afc6.psv"

**Comment by vinhloc1996** [comment]
Sorry for misunderstanding issue. I will test it again for both cases to check it out what went wrong. It might take a day because I'm currently busy. I will announce the result as soon as possible.

**Comment by dderoia** [comment]
All good and absolutely no hurry - I appreciate the effort you put in.  One question - is the source posted the latest ?

**Comment by vinhloc1996** [comment]
Yes, the source code is the latest. It has not updated for a year because I don't see too much problem or need to change something. If you want other features or request to fix the issues, feel free to contribute the pull request and I will add it for you.

**Comment by dderoia** [comment]
Some more info.  If I build from the source in this link https://github.com/vinhloc1996/Decrypt-PluralSight-Videos/archive/1.0.0.0.zip then it runs like a charm.   If I build from the source here .. https://github.com/vinhloc1996/Decrypt-PluralSight-Videos (using Clone or Download - Download zip) then I get the behaviour I have reported. The only material difference I can see in the source is some code around invalid characters and some extended notes in the REAME.md

**Comment by dderoia** [comment]
If I remove the calls to EscapeIllegalCharacters and replace with single line regex then the compiled source works like a charm ….  I'd suggest this therefore constitutes a bug.

Code changes thus :
//newModulePath = this.EscapeIllegalCharacters(newModulePath);
newModulePath = Regex.Replace(newModulePath, "/\\?<>:\\*\\|\\\\\"", "");
and ..
// newPath = this.EscapeIllegalCharacters(newPath);
newPath = Regex.Replace(newPath, "/\\?<>:\\*\\|\\\\\"", "");

**Comment by dderoia** [comment]
I also added this small snippet to have the videos numbers 01, 02 … 10, 11 etc. Such that they are sorted corrected with an alpha sort in directory listings.  Perhaps a request to add this as a feature ??

`newPath = Regex.Replace(newPath, "/\\?<>:\\*\\|\\\\\"", "");
if (Regex.IsMatch(System.IO.Path.GetFileNameWithoutExtension(newPath), "^[0-9]{1}\\. "))
{
                            newPath = Path.Combine(System.IO.Path.GetDirectoryName(newPath), "0" + System.IO.Path.GetFileName(newPath));
                        }`

**Comment by vinhloc1996** [comment]
Hi @dderoia, thank you for pointing me the mistake between the source code and the release one. Can you create the pull request of the source code you had edited? I will test it and merge it to the source branch. Thanks again!

**Comment by dderoia** [comment]
Thanks I'll do that.

**Comment by vinhloc1996** [comment]
Hi @elie-wanko, the problem will be solved by @dderoia pull request, in the meantime, you can download the zip version as @dderoia description to solve the download course problem. The sorted files will be added as soon as possible. Thanks for announcing me the problem.

> Some more info. If I build from the source in this link https://github.com/vinhloc1996/Decrypt-PluralSight-Videos/archive/1.0.0.0.zip then it runs like a charm. If I build from the source here .. https://github.com/vinhloc1996/Decrypt-PluralSight-Videos (using Clone or Download - Download zip) then I get the behaviour I have reported. The only material difference I can see in the source is some code around invalid characters and some extended notes in the README.md

**Comment by dderoia** [comment]
Guys I can work on this in about 4hours from now and get it up. I have never used github before - always bitbucket with Tortoise front end. To save me a bit of time can you give me a couple of pointers on how to get it in place so I can do a pull request. I'm guessing folk and edit that. Just not sure. Thanks.

**Comment by vinhloc1996** [comment]
You can try this [link](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) for more information @dderoia.

**Comment by elie-wanko** [comment]
That's great

**Comment by vinhloc1996** [comment]
Hi @dderoia, I have merged the pull request #9  from you. After checking and testing some course, the problem has been solved and the feature also work perfectly, I've also uploaded version 1.1. Thanks for your supporting. I will close this issue, If you have any request or issue, reopen it and announce me. Thanks again.
